### ISSUE TITLE
Cant use IPV6

### ISSUE THREAD

**Issue by Novalite3D** [throwarray/video-dui#12]
![image](https://user-images.githubusercontent.com/65315474/149224766-bbf18e91-2e11-40b9-87f9-6d97c17062f9.png)

**Comment by Novalite3D** [comment]
I have set up a vps with Ubuntu, and have set up a server that takes over streaming. So it is IPV6. Only this does not work

**Comment by TheIndra55** [comment]
The `SplitHostPort` method in utils.lua should support IPv6 but I cannot test this due to my network adapter not supporting IPv6.

Do you have any pointers or log so we can know where it fails? The "Stream offline" being displayed sounds more like nothing is being played.. Do you see in the clien log "[video-stream] stream online"?

**Comment by Novalite3D** [comment]
Hej @TheIndra55 Ik weet toevallig dat je nederlands bent. Ik heb een VPS opgezet met een server. Zodra ik de link post in het script krijg ik constant dat de stream offline is. Terwijl ik via VLC de zelfde link gewoon kan openen en hij het gewoon doet.

**Comment by Novalite3D** [comment]
Dit is het ding meer

**Comment by Novalite3D** [comment]
Allright, i know the problem but i can fix it. The problem is: Its searching for the default rtmp

**Comment by TheIndra55** [comment]
First of all let's keep it english on here for other people.

Do you have an example of an url you're trying to play? Does regular ffmpeg play it? VLC does some magic sometimes to resolve urls like youtube.

**Comment by Novalite3D** [comment]
rtmp://81.169.231.189:1935/live it the url

**Comment by Novalite3D** [comment]
![image](https://user-images.githubusercontent.com/65315474/149240050-262264bd-29e9-4c33-aebf-7e015e31c796.png)
As you can see, its streaming

**Comment by Malaros** [comment]
![Uploading image.png…]()

**Comment by Novalite3D** [comment]
![image](https://user-images.githubusercontent.com/65315474/149240107-5a2fd929-0968-4002-aa66-dc16b0ed9240.png)

**Comment by TheIndra55** [comment]
If you are streaming to the RTMP server you shouldn't have to enter the link manually anywhere, do you see "[video-stream] stream online" in the client console when you start streaming?

**Comment by Novalite3D** [comment]
Nope i dont see

**Comment by Novalite3D** [comment]
I 'm streaming to an other rtmp server on my vps

**Comment by TheIndra55** [comment]
If you are not using the script RTMP server you must manually play it by using `/video-stream:set "rtmp://81 ..."`

**Comment by Novalite3D** [comment]
![image](https://user-images.githubusercontent.com/65315474/149241896-499ecaa0-f8bf-4044-9534-0905621fcdca.png)

**Comment by Novalite3D** [comment]
I dont have access

**Comment by TheIndra55** [comment]
Execute the command in the console (without slash) or give yourself permissions
```
add_ace identifier.steam:110000112345678 command.video-stream:set allow
```

**Comment by Novalite3D** [comment]
Its working! Thanks man!

**Comment by TheIndra55** [comment]
Great to hear, I will close this topic. If you have any other issues feel free to open a new issue or ask for help on the [forum topic](https://forum.cfx.re/t/release-video-stream-watch-videos-with-your-friends/274274)

**Comment by Novalite3D** [comment]
Allright i still got a problem, i moved the screenCoords() and replaced the name but it doenst seem to move the DUI. How do i fix?
